module Typeable.Taf20e1db8f0d414f90625b1521e41378 where

data Language = AAR{}
              | ABK{}
              | ACE{}
              | ACH{}
              | ADA{}
              | ADY{}
              | AFA{}
              | AFH{}
              | AFR{}
              | AIN{}
              | AKA{}
              | AKK{}
              | ALE{}
              | ALG{}
              | ALT{}
              | AMH{}
              | ANG{}
              | ANP{}
              | APA{}
              | ARA{}
              | ARC{}
              | ARG{}
              | ARN{}
              | ARP{}
              | ART{}
              | ARW{}
              | ASM{}
              | AST{}
              | ATH{}
              | AUS{}
              | AVA{}
              | AVE{}
              | AWA{}
              | AYM{}
              | AZE{}
              | BAD{}
              | BAI{}
              | BAK{}
              | BAL{}
              | BAM{}
              | BAN{}
              | BAS{}
              | BAT{}
              | BEJ{}
              | BEL{}
              | BEM{}
              | BEN{}
              | BER{}
              | BHO{}
              | BIH{}
              | BIK{}
              | BIN{}
              | BIS{}
              | BLA{}
              | BNT{}
              | BOD{}
              | BOS{}
              | BRA{}
              | BRE{}
              | BTK{}
              | BUA{}
              | BUG{}
              | BUL{}
              | BYN{}
              | CAD{}
              | CAI{}
              | CAR{}
              | CAT{}
              | CAU{}
              | CEB{}
              | CEL{}
              | CES{}
              | CHA{}
              | CHB{}
              | CHE{}
              | CHG{}
              | CHK{}
              | CHM{}
              | CHN{}
              | CHO{}
              | CHP{}
              | CHR{}
              | CHU{}
              | CHV{}
              | CHY{}
              | CMC{}
              | COP{}
              | COR{}
              | COS{}
              | CPE{}
              | CPF{}
              | CPP{}
              | CRE{}
              | CRH{}
              | CRP{}
              | CSB{}
              | CUS{}
              | CYM{}
              | DAK{}
              | DAN{}
              | DAR{}
              | DAY{}
              | DEL{}
              | DEN{}
              | DEU{}
              | DGR{}
              | DIN{}
              | DIV{}
              | DOI{}
              | DRA{}
              | DSB{}
              | DUA{}
              | DUM{}
              | DYU{}
              | DZO{}
              | EFI{}
              | EGY{}
              | EKA{}
              | ELL{}
              | ELX{}
              | ENG{}
              | ENM{}
              | EPO{}
              | EST{}
              | EUS{}
              | EWE{}
              | EWO{}
              | FAN{}
              | FAO{}
              | FAS{}
              | FAT{}
              | FIJ{}
              | FIL{}
              | FIN{}
              | FIU{}
              | FON{}
              | FRA{}
              | FRM{}
              | FRO{}
              | FRR{}
              | FRS{}
              | FRY{}
              | FUL{}
              | FUR{}
              | GAA{}
              | GAY{}
              | GBA{}
              | GEM{}
              | GEZ{}
              | GIL{}
              | GLA{}
              | GLE{}
              | GLG{}
              | GLV{}
              | GMH{}
              | GOH{}
              | GON{}
              | GOR{}
              | GOT{}
              | GRB{}
              | GRC{}
              | GRN{}
              | GSW{}
              | GUJ{}
              | GWI{}
              | HAI{}
              | HAT{}
              | HAU{}
              | HAW{}
              | HEB{}
              | HER{}
              | HIL{}
              | HIM{}
              | HIN{}
              | HIT{}
              | HMN{}
              | HMO{}
              | HRV{}
              | HSB{}
              | HUN{}
              | HUP{}
              | HYE{}
              | IBA{}
              | IBO{}
              | IDO{}
              | III{}
              | IJO{}
              | IKU{}
              | ILE{}
              | ILO{}
              | INA{}
              | INC{}
              | IND{}
              | INE{}
              | INH{}
              | IPK{}
              | IRA{}
              | IRO{}
              | ISL{}
              | ITA{}
              | JAV{}
              | JBO{}
              | JPN{}
              | JPR{}
              | JRB{}
              | KAA{}
              | KAB{}
              | KAC{}
              | KAL{}
              | KAM{}
              | KAN{}
              | KAR{}
              | KAS{}
              | KAT{}
              | KAU{}
              | KAW{}
              | KAZ{}
              | KBD{}
              | KHA{}
              | KHI{}
              | KHM{}
              | KHO{}
              | KIK{}
              | KIN{}
              | KIR{}
              | KMB{}
              | KOK{}
              | KOM{}
              | KON{}
              | KOR{}
              | KOS{}
              | KPE{}
              | KRC{}
              | KRL{}
              | KRO{}
              | KRU{}
              | KUA{}
              | KUM{}
              | KUR{}
              | KUT{}
              | LAD{}
              | LAH{}
              | LAM{}
              | LAO{}
              | LAT{}
              | LAV{}
              | LEZ{}
              | LIM{}
              | LIN{}
              | LIT{}
              | LOL{}
              | LOZ{}
              | LTZ{}
              | LUA{}
              | LUB{}
              | LUG{}
              | LUI{}
              | LUN{}
              | LUO{}
              | LUS{}
              | MAD{}
              | MAG{}
              | MAH{}
              | MAI{}
              | MAK{}
              | MAL{}
              | MAN{}
              | MAP{}
              | MAR{}
              | MAS{}
              | MDF{}
              | MDR{}
              | MEN{}
              | MGA{}
              | MIC{}
              | MIN{}
              | MIS{}
              | MKD{}
              | MKH{}
              | MLG{}
              | MLT{}
              | MNC{}
              | MNI{}
              | MNO{}
              | MOH{}
              | MON{}
              | MOS{}
              | MRI{}
              | MSA{}
              | MUL{}
              | MUN{}
              | MUS{}
              | MWL{}
              | MWR{}
              | MYA{}
              | MYN{}
              | MYV{}
              | NAH{}
              | NAI{}
              | NAP{}
              | NAU{}
              | NAV{}
              | NBL{}
              | NDE{}
              | NDO{}
              | NDS{}
              | NEP{}
              | NEW{}
              | NIA{}
              | NIC{}
              | NIU{}
              | NLD{}
              | NNO{}
              | NOB{}
              | NOG{}
              | NON{}
              | NOR{}
              | NQO{}
              | NSO{}
              | NUB{}
              | NWC{}
              | NYA{}
              | NYM{}
              | NYN{}
              | NYO{}
              | NZI{}
              | OCI{}
              | OJI{}
              | ORI{}
              | ORM{}
              | OSA{}
              | OSS{}
              | OTA{}
              | OTO{}
              | PAA{}
              | PAG{}
              | PAL{}
              | PAM{}
              | PAN{}
              | PAP{}
              | PAU{}
              | PEO{}
              | PHI{}
              | PHN{}
              | PLI{}
              | POL{}
              | PON{}
              | POR{}
              | PRA{}
              | PRO{}
              | PUS{}
              | QAA{}
              | QUE{}
              | RAJ{}
              | RAP{}
              | RAR{}
              | ROA{}
              | ROH{}
              | ROM{}
              | RON{}
              | RUN{}
              | RUP{}
              | RUS{}
              | SAD{}
              | SAG{}
              | SAH{}
              | SAI{}
              | SAL{}
              | SAM{}
              | SAN{}
              | SAS{}
              | SAT{}
              | SCN{}
              | SCO{}
              | SEL{}
              | SEM{}
              | SGA{}
              | SGN{}
              | SHN{}
              | SID{}
              | SIN{}
              | SIO{}
              | SIT{}
              | SLA{}
              | SLK{}
              | SLV{}
              | SMA{}
              | SME{}
              | SMI{}
              | SMJ{}
              | SMN{}
              | SMO{}
              | SMS{}
              | SNA{}
              | SND{}
              | SNK{}
              | SOG{}
              | SOM{}
              | SON{}
              | SOT{}
              | SPA{}
              | SQI{}
              | SRD{}
              | SRN{}
              | SRP{}
              | SRR{}
              | SSA{}
              | SSW{}
              | SUK{}
              | SUN{}
              | SUS{}
              | SUX{}
              | SWA{}
              | SWE{}
              | SYC{}
              | SYR{}
              | TAH{}
              | TAI{}
              | TAM{}
              | TAT{}
              | TEL{}
              | TEM{}
              | TER{}
              | TET{}
              | TGK{}
              | TGL{}
              | THA{}
              | TIG{}
              | TIR{}
              | TIV{}
              | TKL{}
              | TLH{}
              | TLI{}
              | TMH{}
              | TOG{}
              | TON{}
              | TPI{}
              | TSI{}
              | TSN{}
              | TSO{}
              | TUK{}
              | TUM{}
              | TUP{}
              | TUR{}
              | TUT{}
              | TVL{}
              | TWI{}
              | TYV{}
              | UDM{}
              | UGA{}
              | UIG{}
              | UKR{}
              | UMB{}
              | UND{}
              | URD{}
              | UZB{}
              | VAI{}
              | VEN{}
              | VIE{}
              | VOL{}
              | VOT{}
              | WAK{}
              | WAL{}
              | WAR{}
              | WAS{}
              | WEN{}
              | WLN{}
              | WOL{}
              | XAL{}
              | XHO{}
              | YAO{}
              | YAP{}
              | YID{}
              | YOR{}
              | YPK{}
              | ZAP{}
              | ZBL{}
              | ZEN{}
              | ZHA{}
              | ZHO{}
              | ZND{}
              | ZUL{}
              | ZUN{}
              | ZXX{}
              | ZZA{}
              deriving (Eq, Ord, Show, Enum)
